/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const leftad = '<br/><iframe src="/html/carousel.html" width="100%" height="220vh" scrolling="no" frameborder="0"></iframe>';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'ProductDoc'
    },
    {
      type: 'html',
      value: leftad,
      className: 'sidebar-title',
    },
  ],
  resdownSidebar: [
    'down',
    {
      type: 'autogenerated',
      dirName: 'ResDownload',
    },
    {
      type: 'html',
      value: leftad,
      className: 'sidebar-title',
    },
  ],
  debugdocSidebar: [
    'debug-doc',
    {
      type: 'autogenerated',
      dirName: 'DebugDoc',
    },
    {
      type: 'html',
      value: leftad,
      className: 'sidebar-title',
    },
  ],
  toolsdocSidebar: [
    'tools',
    {
      type: 'autogenerated',
      dirName: 'ToolsDoc',
    },
    {
      type: 'html',
      value: leftad,
      className: 'sidebar-title',
    },
  ],
};

export default sidebars;
