### final image
FROM nginx:stable-alpine-slim AS runner
RUN rm -rf /etc/nginx/conf.d/default.conf \
    && mkdir -p /web
COPY ../scripts/nginx-web.conf /etc/nginx/conf.d/default.conf
COPY ../build/ /web/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
